#!/bin/bash
set -e

up(){
	VBoxManage startvm vm
}

snapshot(){
	copy vm repo
}

reload(){
	copy repo vm
}

vbm="VBoxManage modifyvm vm"

destroy() {
    read -pr "Are you sure you want to destroy your vm?" answer
    [[ $answer != "y" ]] && exit || rm -r vm/*
}

copy() {
    rsync -Pa "$1/" "$2"
}

init() {
    copy repo vm
    echo "Creating VBox VM..."
    VBoxManage createvm --name vm --ostype Debian_64 --register
    $vbm --bridgeadapter1 wlan0
    $vbm --nic1 bridged
    $vbm --memory 6144
    VBoxManage storagectl vm --name "SATA Controller" --add sata --controller IntelAhci
    VBoxManage storageattach vm --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium vm/disk.vdi
    echo "Copying repo to vm..."
}

"$@"
